site_name: LANFactory
repo_name: AlexanderFengler/LANFactory
repo_url: htps://github.com/AlexanderFengler/LANFactory
edit_uri: edit/main/docs

nav:
  - Home: 
      - Overview: index.md
  - Basic Tutorial:
      - Installation: basic_tutorial/basic_tutorial.ipynb
  - Basic Tutorial / JAX:
      - Installation: basic_tutorial_jax/basic_tutorial_jax.ipynb
  - API:
      - lanfactory: api/lanfactory.md
      - config: api/config.md
      - onnx: api/onnx.md
      - trainers: api/trainers.md
      - utils: api/utils.md

plugins:
  - search
  - autorefs
  - mkdocs-jupyter:
      execute: True
      execute_ignore:
        - basic_tutorial/basic_tutorial.ipynb
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/objects.inv
            - https://mkdocstrings.github.io/griffe/objects.inv
          options:
            show_submodules: true
            separate_signature: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
            docstring_style: "numpy"
            docstring_section_style: "list"
            show_root_members_full_path: true
            show_object_full_path: false
            show_category_heading: true
            show_signature_annotations: false
            show_source: false
            group_by_category: false
            signature_crossrefs: true

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.top
    - content.code.copy
    - content.action.view
    - content.action.edit
    - header.autohide
    - announce.dismiss
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to automatic mode

extra:
  homepage: "https://AlexanderFengler.github.io/LANFactory/"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg