wandb_version: 1

cpu_batch_size:
  desc: null
  value: 128
gpu_batch_size:
  desc: null
  value: 128
n_epochs:
  desc: null
  value: 20
optimizer:
  desc: null
  value: adam
learning_rate:
  desc: null
  value: 0.002
lr_scheduler:
  desc: null
  value: reduce_on_plateau
lr_scheduler_params:
  desc: null
  value: {}
weight_decay:
  desc: null
  value: 0.0
loss:
  desc: null
  value: bcelogit
save_history:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697048922.982095
    t:
      1:
      - 1
      - 5
      - 12
      - 45
      - 53
      - 55
      2:
      - 1
      - 5
      - 12
      - 45
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
