name: Run tests

on:
  pull_request:
  push:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: pip install -e .[dev]

      - name: Check styling
        run: black . --check

      - name: Linting
        run: ruff check . --line-length 120 --exclude notebooks/*

    #   - name: Run pytest
    #     run: pytest

      # - name: Build Docs
      #   run: mkdocs build
