name: Run tests

on:
  pull_request:
  push:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: pip install -e .[dev]

      - name: Check styling
        run: black . --check

      - name: Linting
        run: ruff check . --line-length 120 --exclude "notebooks/*" "docs/basic_tutorial/basic_tutorial.ipynb"

    #   - name: Run pytest
    #     run: pytest

      # - name: Build Docs
      #   run: mkdocs build
